var DATA_KEY = 'fabui.fabgrid';
var EVENT_NAMESPACE = '.fabgrid';
var GRID_EVENTS = [
  'autoGeneratedColumns',
  'autoSizedColumn',
  'autoSizedRow',
  'autoSizingColumn',
  'autoSizingRow',
  'beforeLoad',
  'beginningEdit',
  'bigCheckboxesChanged',
  'cellEditEnding',
  'cellEditEnded',
  'columnGroupCollapsedChanged',
  'columnGroupCollapsedChanging',
  'copied',
  'copiedCell',
  'copying',
  'copyingCell',
  'deletedRow',
  'deletingRow',
  'draggedColumn',
  'draggedRow',
  'draggingColumn',
  'draggingRow',
  'formatItem',
  'groupCollapsedChanged',
  'groupCollapsedChanging',
  'itemsSourceChanged',
  'itemsSourceChanging',
  'loadedRows',
  'loadingRows',
  'loadError',
  'loadSuccess',
  'pageChanged',
  'pageChanging',
  'pasted',
  'pastedCell',
  'pasting',
  'pastingCell',
  'prepareCellForEdit',
  'refreshed',
  'refreshing',
  'resizedColumn',
  'resizedRow',
  'resizingColumn',
  'resizingRow',
  'rowAdded',
  'rowEditEnded',
  'rowEditEnding',
  'rowEditStarted',
  'rowEditStarting',
  'scrollPositionChanged',
  'selectionChanged',
  'selectionChanging',
  'sortedColumn',
  'sortingColumn',
  'updatedLayout',
  'updatedView',
  'updatingLayout',
  'updatingView'
];

var SETTER_METHODS = {
  activeCellBorder: 'setActiveCellBorder',
  columns: 'setColumns',
  frozenColumns: 'setFrozenColumns',
  frozenRightColumns: 'setFrozenRightColumns',
  itemsSource: 'setItemsSource',
  locale: 'setLocale',
  showFooter: 'setShowFooter',
  showRowHeaders: 'setShowRowHeaders'
};

export function toJQueryEventName(value) {
  return String(value || '').toLowerCase();
}

export function isPublicMethod(instance, name) {
  return Boolean(instance && typeof name === 'string' && name.charAt(0) !== '_' && typeof instance[name] === 'function');
}

export function createFabGridJQuery($, fabui) {
  if (!$ || !$.fn) throw new Error('fabgrid-jquery requires jQuery.');
  if (!fabui || typeof fabui.FabGrid !== 'function') throw new Error('fabgrid-jquery requires fabui.FabGrid.');

  function getInstance(element) {
    return $.data(element, DATA_KEY);
  }

  function setInstance(element, instance) {
    $.data(element, DATA_KEY, instance);
  }

  function removeInstance(element) {
    $.removeData(element, DATA_KEY);
  }

  function triggerLifecycle(element, name, instance) {
    $(element).triggerHandler(name + EVENT_NAMESPACE, [instance]);
  }

  function unbindCoreEvents(instance) {
    var bindings = instance.__fabgridJQueryBindings || [];
    bindings.forEach(function(binding) {
      binding.event.removeHandler(binding.handler, instance);
    });
    delete instance.__fabgridJQueryBindings;
  }

  function bindCoreEvents(element, instance, options) {
    var bindings = [];
    GRID_EVENTS.forEach(function(name) {
      var coreEvent = instance[name];
      var handler;
      if (!coreEvent || typeof coreEvent.addHandler !== 'function') return;
      handler = function(sender, args) {
        var event = $.Event(toJQueryEventName(name) + EVENT_NAMESPACE);
        var callback = options && options[name];
        args = args || {};
        $(element).triggerHandler(event, [args, instance]);
        if (typeof callback === 'function' && callback.call(element, event, args, instance) === false) {
          args.cancel = true;
        }
        if (event.isDefaultPrevented && event.isDefaultPrevented()) args.cancel = true;
        return args.cancel !== true;
      };
      coreEvent.addHandler(handler, instance);
      bindings.push({ event: coreEvent, handler: handler });
    });
    instance.__fabgridJQueryBindings = bindings;
  }

  function setOption(instance, name, value) {
    var setter = SETTER_METHODS[name];
    if (setter && typeof instance[setter] === 'function') {
      instance[setter](value);
      return;
    }
    if (name in instance && typeof instance[name] !== 'function') {
      instance[name] = value;
      return;
    }
    instance.options[name] = value;
    if (typeof instance.invalidate === 'function') instance.invalidate();
  }

  function setOptions(instance, options) {
    Object.keys(options || {}).forEach(function(name) {
      if (GRID_EVENTS.indexOf(name) >= 0) return;
      setOption(instance, name, options[name]);
    });
  }

  function getOption(instance, name) {
    if (name in instance && typeof instance[name] !== 'function') return instance[name];
    return instance.options ? instance.options[name] : undefined;
  }

  function create(element, options) {
    var instance = new fabui.FabGrid(element, options || {});
    setInstance(element, instance);
    bindCoreEvents(element, instance, options || {});
    triggerLifecycle(element, 'initialized', instance);
    return instance;
  }

  function destroy(element, instance) {
    if (!instance) return;
    unbindCoreEvents(instance);
    if (typeof instance.dispose === 'function') instance.dispose();
    removeInstance(element);
    triggerLifecycle(element, 'destroyed', instance);
  }

  function plugin(command) {
    var args = Array.prototype.slice.call(arguments, 1);
    var first = this[0];
    var instance;
    var result;

    if (typeof command !== 'string') {
      return this.each(function() {
        var current = getInstance(this);
        if (current) setOptions(current, command || {});
        else create(this, command || {});
      });
    }

    if (command === 'instance') return first ? getInstance(first) : undefined;
    if (command === 'option' && args.length === 1 && typeof args[0] === 'string') {
      instance = first ? getInstance(first) : null;
      return instance ? getOption(instance, args[0]) : undefined;
    }

    this.each(function() {
      var current = getInstance(this);
      if (!current) throw new Error('Cannot call fabgrid method before initialization: ' + command);
      if (command === 'destroy') {
        destroy(this, current);
        return;
      }
      if (command === 'option') {
        if (typeof args[0] === 'string') setOption(current, args[0], args[1]);
        else setOptions(current, args[0] || {});
        return;
      }
      if (!isPublicMethod(current, command)) throw new Error('Unknown or private fabgrid method: ' + command);
      result = current[command].apply(current, args);
    });

    return result === undefined ? this : result;
  }

  $.fn.fabgrid = plugin;

  return {
    dataKey: DATA_KEY,
    eventNamespace: EVENT_NAMESPACE,
    getInstance: getInstance,
    destroy: function(element) { destroy(element, getInstance(element)); }
  };
}

export default createFabGridJQuery;
